[package]
name = "harxes-cli"
version.workspace = true
edition.workspace = true

[dependencies]
harxes-core-domain  = { path = "../core-domain" }
harxes-app          = { path = "../app" }
harxes-infra-shell  = { path = "../infra-shell" }
harxes-infra-llm    = { path = "../infra-llm" }
harxes-infra-session= { path = "../infra-session" }
harxes-infra-auth   = { path = "../infra-auth" }
harxes-infra-fs     = { path = "../infra-fs" }

[dependencies.clap]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.syntect]
workspace = true

[dependencies.ratatui]
workspace = true

[dependencies.crossterm]
workspace = true
